// Compiles GLSL to SPIR-V with glslang and writes a C++ header of uint32 arrays.
//
// Usage:
//   node compile.cjs <out.h> <stage|input.glsl|symbol> [...]
//
//   stage   vertex | fragment | compute   (glslang stage names)
//   symbol  C++ identifier for the generated array
//
// Requires: npm --prefix tools/shaders ci

const fs = require("fs");
const path = require("path");
const init = require("@webgpu/glslang");

const [, , outFile, ...specs] = process.argv;
if (!outFile || specs.length === 0) {
  console.error("usage: node compile.cjs <out.h> <stage|input.glsl|symbol> [...]");
  process.exit(2);
}

const WORDS_PER_LINE = 8;

init()
  .then((glslang) => {
    const lines = [
      "// Generated by tools/shaders/compile.cjs. Do not edit.",
      "#pragma once",
      "",
      "#include <cstddef>",
      "#include <cstdint>",
      "",
      "namespace Raven::Render::Shaders",
      "{",
    ];

    for (const spec of specs) {
      const [stage, input, symbol] = spec.split("|");
      if (!stage || !input || !symbol) {
        throw new Error(`bad spec '${spec}' (expected stage|input|symbol)`);
      }
      const source = fs.readFileSync(input, "utf8");
      const words = glslang.compileGLSL(source, stage);
      if (!words || words.length === 0) {
        throw new Error(`glslang produced no SPIR-V for ${input}`);
      }

      lines.push(`    // ${input} (${stage}) -> ${words.length} words`);
      lines.push(`    inline constexpr std::uint32_t ${symbol}[] =`);
      lines.push("    {");
      for (let i = 0; i < words.length; i += WORDS_PER_LINE) {
        const chunk = Array.from(words.slice(i, i + WORDS_PER_LINE), (w) =>
          "0x" + (w >>> 0).toString(16).padStart(8, "0"));
        lines.push("        " + chunk.join(", ") + ",");
      }
      lines.push("    };");
      lines.push("");
    }

    lines.push("}");
    lines.push("");
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, lines.join("\n"));
    console.log(`wrote ${outFile} (${specs.length} shader(s))`);
    process.exit(0);
  })
  .catch((err) => {
    console.error("shader compile failed:", err.message || err);
    process.exit(1);
  });
